"use client";

import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import "aos/dist/aos.css"; // Import AOS styles
import AOS from "aos";
import { useEffect } from "react";
import CustomCursor from "./customCursor";
import { usePathname } from "next/navigation";
import { SessionProvider } from "next-auth/react";
import Footer from "@/components/footer/Footer";

// ini adalah cara pengunaan local font
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const disableNavbar = ["/login", "/register"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    AOS.init({ duration: 1000 }); // Initialize AOS with default duration
  }, []);
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={`bg-gray-900 ${poppins.className}`}>
        <SessionProvider>
          <CustomCursor />
          {!disableNavbar.includes(pathname) && <Navbar />}
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
